baseURL = 'https://bestend.github.io/'
languageCode = 'en'
title = 'Bestend'
theme = 'yinyang'

[params]
description = 'Software development and open source'
mainSections = ['posts']

[params.author]
name = 'Bestend'

[[params.social]]
name = 'GitHub'
url = 'https://github.com/bestend'

[[params.social]]
name = 'Email'
url = 'mailto:infend@gmail.com'

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts/'
weight = 2

[[menu.main]]
name = 'About'
url = '/about/'
weight = 3


